sonar.projectKey=Sertion_vscode-gitblame
sonar.organization=sertion

sonar.javascript.lcov.reportPaths=lcov.info
sonar.typescript.tsconfigPaths=./tsconfig.json
sonar.sources=./src/,./.github/
sonar.tests=./test/
