name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node Dependencies
        run: npm ci

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Code quality
        run: biome ci ./src/

      - name: Run tests
        run: xvfb-run -a npm test
